---
- name: Check if the node exists in the cluster
  command: kubectl get node "{{ ansible_hostname }}" --no-headers
  register: node_check
  failed_when: node_check.rc not in [0, 1]
  ignore_errors: true
  delegate_to: "{{ groups['master'][0] }}"

- name: Initialize Kubernetes master
  command: "kubeadm init --pod-network-cidr={{ pod_cidr }}"
  register: kubeadm_output
  when: node_check.rc != 0
  ignore_errors: true

- name: Set up kubectl for the current user
  command: "{{ item }}"
  with_items:
    - "mkdir -p $HOME/.kube"
    - "cp /etc/kubernetes/admin.conf $HOME/.kube/config"
    - "chown $USER $HOME/.kube/config"

- name: Install Calico network plugin
  command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml

- name: Check if control plane node is already tainted
  command: kubectl get node {{ ansible_hostname }} -o jsonpath='{.spec.taints}'
  delegate_to: "{{ groups['master'][0] }}"
  register: taint_check
  changed_when: false

- name: Taint control plane to avoid pods running on it
  command: kubectl taint nodes {{ ansible_hostname }} node-role.kubernetes.io/control-plane=:NoSchedule
  delegate_to: "{{ groups['master'][0] }}"
  when: "'node-role.kubernetes.io/control-plane' not in taint_check.stdout"